wip

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -55,6 +55,11 @@ jobs:
       run: |
         PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c 'CREATE EXTENSION IF NOT EXISTS vector;' || exit 1
 
+    - name: Install River CLI
+      run: |
+        go install github.com/riverqueue/river/cmd/river@latest
+        which river || echo "River installation failed"
+
     - name: Install dependencies
       run: go mod download
 
